language: cpp
compiler:
    - clang
    - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - valgrind
      - cppcheck
      - build-essential
env:
    - STATSD_COMPILE_MODE=Debug
    - STATSD_COMPILE_MODE=Release
branches:
  only: 
    - master
os:
    - linux
    - osx
    - windows
matrix:
    allow_failures:
        - os: windows
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install make cmake cppcheck
        ;;
      linux)
        sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
        ;;
    esac
script: make test STATSD_COMPILE_MODE=$STATSD_COMPILE_MODE
after_script: make lint
